name: Deploy to Linux Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Build Astro project
      run: npm run build

    - name: Clean target directory
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa
        chmod 600 id_rsa
        ssh -i id_rsa -o StrictHostKeyChecking=no -p 222 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "rm -rf /var/www/kevinatruong.com/html/*" -v

    - name: Deploy to Server
      run: |
        scp -i id_rsa -o StrictHostKeyChecking=no -P 222 -r dist/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/kevinatruong.com/html/

          
