name: Deploy to Linux Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Build Astro project
      run: npm run build

    - name: Deploy to server
      env:
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_PORT: ${{ secrets.SERVER_PORT }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa
        chmod 600 id_rsa
        scp -P $SERVER_PORT -r dist/* $SERVER_USER@$SERVER_IP:$DEPLOY_PATH
        rm id_rsa


